"""
GeoJSON → KML converter for Google Earth verification.

Generates a KML file with 3015 lot polygons color-coded by product kind,
ready to drag-drop into Google Earth Pro Desktop.

USAGE:
    python scripts/geojson-to-kml.py \\
        --input  data/geometry/cdt-lots-4326.geojson \\
        --output data/geometry/cdt-lots-4326.kml
"""
import argparse
import json
import os
import sys


# KML color is AABBGGRR (alpha, blue, green, red) — opposite of CSS
KIND_COLOR = {
    'villa-don-lap':  '7f0000ff',  # red       (translucent)
    'villa-song-lap': '7f00aaff',  # orange
    'shophouse':      '7f00ffff',  # yellow
    'townhouse':      '7f00ff00',  # green
    'subdivision-zone': '5fff00ff',  # magenta
    'road':           'ff999999',  # gray
    'sidewalk':       'ffcccccc',  # light gray
    'setback':        '7fffaaaa',  # pale red
}


def feat_to_placemark(feat, idx):
    props = feat.get('properties', {})
    kind = props.get('kind', 'unknown')
    color = KIND_COLOR.get(kind, '7fffffff')
    cdt_id = props.get('cdt_id', f'lot_{idx}')
    area = props.get('area_cad_m2', '?')
    name = f"{cdt_id} ({kind}, {area} m²)"

    rings = feat['geometry']['coordinates']
    outer = rings[0]
    coords_str = ' '.join(f'{pt[0]:.7f},{pt[1]:.7f},0' for pt in outer)

    return f'''
    <Placemark>
      <name>{name}</name>
      <styleUrl>#kind_{kind}</styleUrl>
      <ExtendedData>
        <Data name="kind"><value>{kind}</value></Data>
        <Data name="cdt_id"><value>{cdt_id}</value></Data>
        <Data name="area_m2"><value>{area}</value></Data>
      </ExtendedData>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>{coords_str}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>'''


def build_styles():
    out = []
    for kind, color in KIND_COLOR.items():
        out.append(f'''
    <Style id="kind_{kind}">
      <LineStyle><color>ff333333</color><width>1</width></LineStyle>
      <PolyStyle><color>{color}</color><fill>1</fill><outline>1</outline></PolyStyle>
    </Style>''')
    return ''.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--input', required=True)
    ap.add_argument('--output', required=True)
    ap.add_argument('--name', default='Hồng Hạc City — CDT QH05.2 Lots')
    args = ap.parse_args()

    with open(args.input, 'r', encoding='utf-8') as f:
        doc = json.load(f)

    features = doc.get('features', [])
    placemarks = ''.join(feat_to_placemark(f, i) for i, f in enumerate(features))
    styles = build_styles()

    kml = f'''<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>{args.name}</name>
    <description>3015 lot polygons from CDT QH05.2 plan, transformed VN-2000 → EPSG:4326. Generated by scripts/geojson-to-kml.py.</description>
    {styles}
    {placemarks}
  </Document>
</kml>
'''

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(kml)

    sz = os.path.getsize(args.output)
    print(f"[OK] {args.output}  ({sz/1024/1024:.2f} MB, {len(features)} placemarks)")
    print("Drag-drop into Google Earth Pro Desktop to verify alignment.")


if __name__ == '__main__':
    main()
